- name: Deploy Nginx, PostgreSQL und Express mit Docker Compose
  hosts: localhost
  become: true

  tasks:
    - name: Kopiere `docker-compose.yml`
      copy:
        src: ./docker-compose.yml
        dest: /opt/deployment/docker-compose.yml
        mode: "0644"

    - name: Starte Docker-Container mit Compose
      community.docker.docker_compose:
        project_src: /opt/deployment/
        state: present
        restarted: true

    - name: Warte, bis der Backend-Dienst erreichbar ist
      wait_for:
        host: "localhost"
        port: 3000
        timeout: 30

