- name: Deployment von Nginx, PostgreSQL und Express mit Docker Compose
  hosts: localhost
  become: true
  vars_files:
    - vault/secrets.yaml
  roles:
    - common
    - postgres
    - backend
    - nginx
    
   

