# Allgemeine Variablen für das Projekt

# PostgreSQL
postgres_container: "postgres_container"
postgres_user: "postgres_testuser"
postgres_password: "testpass"
postgres_db: "postgres_test_db"
postgres_port: 5432

# Backend
backend_port: 3000

# Nginx
nginx_port: 8080


